# Generated by Django 5.0.6 on 2024-07-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0017_sucursal_tecnico_mantencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='estado',
            field=models.CharField(choices=[('Aceptado para reparar', 'Aceptado para reparar'), ('Cancelado', 'Cancelado'), ('En reparacion', 'En reparacion'), ('Mantencion solicitada', 'Mantencion solicitada'), ('Reparado', 'Reparado')], default='Mantencion solicitada', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Aceptado para reparar', 'Aceptado para reparar'), ('Cancelado', 'Cancelado'), ('En reparacion', 'En reparacion'), ('Mantencion solicitada', 'Mantencion solicitada'), ('Reparado', 'Reparado')], default='Pagado', max_length=50),
        ),
    ]
